name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Lint with ruff
        run: |
          . .venv/bin/activate
          ruff check .

      - name: Format check with black
        run: |
          . .venv/bin/activate
          black --check .

      - name: Type check with mypy
        run: |
          . .venv/bin/activate
          mypy .

      - name: Run tests with pytest
        run: |
          . .venv/bin/activate
          pytest
